### ISSUE TITLE
fontColor颜色设置不生效了

### ISSUE THREAD

**Issue by github-ace** [wangqiangstar/watermark-component#1]
请把具体调用和表现贴一下，我定位下问题，配置项fontColor: '#727071'严格使用字符串格式

**Comment by wangqiangstar** [comment]
请把具体调用和表现贴一下，我定位下问题，配置项f`ontColor: '#727071'`严格使用字符串格式

**Comment by github-ace** [comment]
[![Edit upbeat-booth-ty8n6](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upbeat-booth-ty8n6?fontsize=14&hidenavigation=1&theme=dark)
用了一个蓝色，但是没生效，上面是链接

**Comment by wangqiangstar** [comment]
我试了下，是可以生效的，ReadMe文档写的有误导哈！！！，见谅！，我更新了使用文档

**Comment by github-ace** [comment]
我也生效了，感谢

**Comment by github-ace** [comment]
[![Edit upbeat-booth-ty8n6](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upbeat-booth-ty8n6?fontsize=14&hidenavigation=1&theme=dark)
旋转角度为0的时候，顶部少了一半
